version: "3.7"

services:

    # Node JS Todo App
    # Docker Command:
        # docker run -dp 3000:3000 `
        #     -w /app -v "$(pwd):/app" `
        #     --network todo-app `
        #     -e MYSQL_HOST=mysql `
        #     -e MYSQL_USER=root `
        #     -e MYSQL_PASSWORD=secret `
        #     -e MYSQL_DB=todos `
        #     node:12-alpine `
        #     sh -c "yarn install && yarn run dev"
    app:
        image: node:12-alpine
        command: sh -c "yarn install && yarn run dev"
        ports:
            - 3000:3000
        working_dir: /app
        # Mount content of current dir to /app on container -> Allow reload without rebuilding
        volumes:
            - ./:/app
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_DB: todos
    
    # My SQL Server
    # Docker Command:
    # docker run -d `
    #     --network todo-app --network-alias mysql `
    #     -v todo-mysql-data:/var/lib/mysql `
    #     -e MYSQL_ROOT_PASSWORD=secret `
    #     -e MYSQL_DATABASE=todos `
    #     mysql:5.7
    mysql:
        image: mysql:5.7
        volumes: 
            - todo-mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: todos

# Create named volume to be used by sql server
volumes:
    todo-mysql-data: